# Nome da Actions:
name: Snake Game

# Controlador do tempo que será feita a atualização dos arquivos.
on:
  schedule:
    # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

  # Permite executar manualmente na aba Actions (para testes).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # dá permissão de escrita ao GITHUB_TOKEN

    steps:
      # Faz checkout do repositório
      - uses: actions/checkout@v3

      # Gera os arquivos da cobra
      - uses: Platane/snk@master
        with:
          github_user_name: GabrielGGC18
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publica os arquivos na branch "output"
      - name: Deploy snake files
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
